apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-test-rabbit
  region: us-west-2

vpc:
  cidr: 172.20.0.0/16

nodeGroups:
  - name: ng-1-backend
    labels: { role: workers }
    instanceType: t3a.large
    minSize: 2
    desiredCapacity: 3
    maxSize: 3
    privateNetworking: true
    volumeSize: 30