apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    git: https://charts.jetstack.io/cert-manager
    ref: v0.13.0
    path: charts/jetstack/cert-manager